### PR TITLE
Update ws init lint formatting

### PR DESCRIPTION
**Pull request by justinpolygon**
Attempting to fix lint formatting issue with https://github.com/polygon-io/client-python/pull/658.

### CODE REVIEW

**Comment by justinpolygon** [comment]
Hey @jbonzo is there a way to merge this even though the lint check doesn't pass? What seems to be happening is that the current check is testing against `black (23.12.1)` and failing. I need this to merge to update the `black` version in https://github.com/polygon-io/client-python/pull/658 wants a different style of lint for `black (24.4.2)`.

So, I'm running into this issue where I cannot update the dependancy to fix the depedancy. Or, is it as simple as approving and we merge something that doesn't pass a lint check?

**Comment by jbonzo** [comment]
> Hey @jbonzo, I'm facing a dependency deadlock due to the lint check failing against `black (23.12.1)`. I need to merge the current PR to then update the `black` version to `24.4.2` as required by [this PR](https://github.com/polygon-io/client-python/pull/658), which wants a different linting style. Can we merge this PR even if the lint check doesn't pass, or is there a workaround to update the lint check that could resolve this issue? What are your thoughts on proceeding with a merge that doesn't pass the lint check?

@justinpolygon Is there something preventing us from putting the comprehensive fix in this single PR?

**Comment by justinpolygon** [comment]
> @justinpolygon Is there something preventing us from putting the comprehensive fix in this single PR?

Doh, that's such a good idea! I just needed a second set of eyes. Yeah, I'll test that. Thank you!

**Comment by justinpolygon** [comment]
That fixed it. Thanks @jbonzo!

**Review by jbonzo — APPROVED** [review]

**Comment by justinpolygon** [comment]
Thanks again for the suggestion and help @jbonzo! Cheers.

**Review by PeTty88cze — COMMENTED** [review]
PeTty

**Review by PeTty88cze — APPROVED** [review]

**Pull request merged**
